name: bitfinex-api-py-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install bitfinex-api-py's dependencies
        run: python -m pip install -r dev-requirements.txt
      - name: Lint the project with pylint (and fail if score is lower than 10.00/10.00)
        run: python -m pylint bfxapi
      - name: Run mypy to check the correctness of type hinting (and fail if any error or warning is found)
        run: python -m mypy bfxapi
